app:
    verbose: False
    fps: 4
    confidence: null
    overlay:
        enabled: True
        show_detections: False
        monitor: null
    debug:
        enable: False
        profiler: False
        inspect:
            full_frame:
                enable: False
                file_path: screenshots/last_frame.png
                interval: 1
            digit_reader_frame:
                enable: False
                file_path: screenshots/last_digit_reader_frame.png
            ping_detection:
              enable: False
              file_path: screenshots/last_ping_detection.png
    training:
        save: null
        save_dir: captures
        labels: ['Ping - Scan']
        min_capture_interval: 3.0
    ai:
        device: cuda
        detector:
            model: scanner.pt
        reader:
            model: digit_reader.pt

      
