openai:
  api_key: "${private.openai.api_key}"
  api_base: "https://api.openai.com/v1"

uexcorp:
  bearer_token: "${private.uexcorp.bearer_token}"

# Text-to-Speech settings
tts:
  # Default public Kokoro model repo id. Override here if you want another model
  model_id: "hexgrad/Kokoro-82M"
  # Optionally preload voices. Examples: ["af_sky", "af_sky,af_heart"]
  # Note: kororo supports merging voice weights into an aggregate weight with commas
  voices: ["af_sky,af_heart"]

stt:
  model_id: "gpt-4o-mini-transcribe"

openwakeword:
  inference_framework: "onnx"
  models:
    - name: "mining_logger"
      path: "./resources/models/mining_logger.onnx"
      wake_word_key: "mining_logger"
      confirmation_audio: "./resources/audio/activation.wav"
    - name: "scan_this"
      path: "./resources/models/scan_this.onnx"
      wake_word_key: "scan_this"
      confirmation_audio: "./resources/audio/scan.mp3"
      suppress_follow_up: true
    - name: "stop"
      path: "./resources/models/stop.onnx"
      suppress_follow_up: true
    - name: "analyze_ping"
      path: "./resources/models/analyze_ping.onnx"
      confirmation_audio: "./resources/audio/scan.mp3"
      suppress_follow_up: true