openai:
  api_key: "${private.openai.api_key}"
  api_base: "https://api.openai.com/v1"

uexcorp:
  bearer_token: "${private.uexcorp.bearer_token}"

# Text-to-Speech settings
tts:
  # Default public Kokoro model repo id. Override here if you want another model
  model_id: "hexgrad/Kokoro-82M"
  # Optionally preload voices. Examples: ["af_sky", "af_sky,af_heart"]
  # Note: kororo supports merging voice weights into an aggregate weight with commas
  voices: ["af_sky,af_heart"]

openwakeword:
  inference_framework: "onnx"
  models:
    - name: "agent"
      path: "./resources/models/mining_logger.onnx"
    - name: "scan"
      path: "./resources/models/scan_this.onnx"
    - name: "stop"
      path: "./resources/models/stop.onnx"
    - name: "ping"
      path: "./resources/models/analyze_ping.onnx"